---
---
# __Table of Contents__


## __Data Cleaning & Fixing__

### __1. Library Imports__
* __Data Manipulation:__ `pandas` to structure and clean your numbers.

### __2. Structural Checks & Header Standardization__
1. Working on `train.csv` dataset
2. Working on `test.csv` dataset 
---
---

### __Data Dictionary__

|Variable	|Definition	        |Key                                              |
|:----------|:------------------|:------------------------------------------------|
|PassengerId|Passenger ID       |
|Survived	|Survival	        |0 = No, 1 = Yes                                  |
|Pclass	    |Ticket class       |1 = 1st, 2 = 2nd, 3 = 3rd                        |
|Name       |Name of person     |
|Sex	    |Sex	            |
|Age	    |Age in years       |	
|SibSp	    |# of siblings / spouses aboard the Titanic|
|Parch	    |# of parents / children aboard the Titanic|
|Ticket	    |Ticket number      |
|Fare	    |Passenger fare     |	
|Cabin	    |Cabin number       |	
|Embarked	|Port of Embarkation|	C = Cherbourg, Q = Queenstown, S = Southampton|


### __Variable Notes__

__Pclass:__ A proxy for socio-economic status (SES)
* 1st = Upper
* 2nd = Middle
* 3rd = Lower

__Age:__ Age is fractional if less than 1. If the age is estimated, is it in the form of xx.5

__SibSp:__ The dataset defines family relations in this way...
* Sibling = brother, sister, stepbrother, stepsister
* Spouse = husband, wife (mistresses and fiancés were ignored)

__Parch:__ The dataset defines family relations in this way...
* Parent = mother, father
* Child = daughter, son, stepdaughter, stepson
* Some children travelled only with a nanny, therefore parch=0 for them.

### __1. Library Imports__
---

In [1]:
# Data manipulation and calculations
import pandas as pd

### __2. Structural Checks & Header Standardization__
---

### __2.1 Working on `train.csv` dataset__

#### __Load the Dataset__

In [2]:
# Import the 'train.csv' dataset
train_df = pd.read_csv('../data/1-raw/train.csv')

In [3]:
# Show the first 5 rows of data
train_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
# Get a structural breakdown of the dataset
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [5]:
# Check the exact dimensions of the data
train_df.shape

(891, 12)

In [6]:
# Check column names
train_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [7]:
# Convert all column headers to lowercase
train_df.columns = train_df.columns.str.lower()

# Rename the specific columns by hand using a mapping dictionary
rename_dict = {
    'passengerid': 'passenger_id',
    'survived': 'survival',
    'pclass': 'ticket_class',
    'sibsp': 'siblings_spouses',
    'parch': 'parents_children',
    'embarked': 'boarding_port'
}

train_df = train_df.rename(columns=rename_dict)

# Check column names
train_df.columns

Index(['passenger_id', 'survival', 'ticket_class', 'name', 'sex', 'age',
       'siblings_spouses', 'parents_children', 'ticket', 'fare', 'cabin',
       'boarding_port'],
      dtype='object')

#### __Saveing the Changes__

In [8]:
# Save the data into under-process folder
train_df.to_csv('../data/2-under-process/train.csv', index=False)

### __2.2 Working on `test.csv` dataset__

#### __Load the Dataset__

In [9]:
# Import the 'test.csv' dataset
test_df = pd.read_csv('../data/1-raw/test.csv')

In [10]:
# Show the first 5 rows of the data
test_df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [11]:
# Get a structural breakdown of the dataset
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.1+ KB

In [12]:
# Check the exact dimensions of the data
test_df.shape

(418, 11)

In [13]:
# Check the column names
test_df.columns

Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [14]:
# Convert all column headers to lowercase
test_df.columns = test_df.columns.str.lower()

# Rename the specific columns by hand using a mapping dictionary
rename_dict = {
    'passengerid': 'passenger_id',
    'pclass': 'ticket_class',
    'sibsp': 'siblings_spouses',
    'parch': 'parents_children',
    'embarked': 'boarding_port'
}

test_df = test_df.rename(columns=rename_dict)

# Check column names
test_df.columns

Index(['passenger_id', 'ticket_class', 'name', 'sex', 'age',
       'siblings_spouses', 'parents_children', 'ticket', 'fare', 'cabin',
       'boarding_port'],
      dtype='object')

#### __Saveing the Changes__

In [15]:
# Save the data into under-process folder
test_df.to_csv('../data/2-under-process/test.csv', index=False)